export { analyze } from './analyzer/analyzer.js'
export type { AnalyzerOptions, AnalyzerResult } from './analyzer/analyzer.js'
export { ConfigError, loadConfig } from './config/load-config.js'
export type { Diagnostic, Finding, Logger, Rule, RuleContext, RuleListeners, Severity } from './core/index.js'
export { ConsoleLogger } from './core/index.js'
export { buildJsonOutput, renderJson } from './reporters/json-reporter.js'
export { ALL_RULES, getRuleById } from './rules/registry.js'
export { run } from '@oclif/core'
